language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

repos:
  XRAN: https://xran.yihui.name

before_install:
  - "curl https://xran.yihui.name/.gitconfig -o ~/.gitconfig"
  - Rscript -e "if (!require('covr')) install.packages('covr')"

after_success:
  - "(curl https://xran.yihui.name/r-xran | bash)"
  - Rscript -e 'covr::coveralls()'
